import './globals.css'
import { Inter } from 'next/font/google'
import { initializeApp } from "firebase/app";
import { collection, getDocs, getFirestore } from "firebase/firestore"; 
import firebaseConfig from '@root/firebase/config'; 

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const querySnapshot = await getDocs(collection(db, "dates"));
console.log(querySnapshot.docs.map(doc => doc.data()));

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
